
# More info at https://github.com/necojackarc/auto-request-review
reviewers:
  defaults:
    - evan-forbes
    - rach-id
    - tzdybal

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false
