pull_request_rules:
  - name: backport patches to main
    conditions:
      - label=backport-to-main
    actions:
      backport:
        branches:
          - main
  - name: backport patches to v0.39.x
    conditions:
      - label=backport-to-v0.39.x
    actions:
      backport:
        branches:
          - v0.39.x
  - name: backport patches to v0.38.x-celestia
    conditions:
      - label=backport-to-v0.38.x
    actions:
      backport:
        branches:
          - v0.38.x-celestia
  - name: backport patches to v0.34.x-celestia
    conditions:
      - label=backport-to-v0.34.x
    actions:
      backport:
        branches:
          - v0.34.x-celestia
