queue_rules:
  - name: default
    conditions:
      - base=v0.34.x-celestia
      - label=S:automerge

pull_request_rules:
  - name: Automerge to v0.34.x-celestia
    conditions:
      - base=v0.34.x-celestia
      - label=S:automerge
    actions:
      queue:
        method: squash
        name: default
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body }}

  - name: Backport to v0.34.x-celestia
    conditions:
      - base=main
      - label=S:backport-to-v0.34.x
      - merged
    actions:
      backport:
        branches:
          - v0.34.x-celestia
