# Verify that important design docs have ToC entries.
name: Check documentation ToC
on:
  pull_request:
  merge_group:
  push:
    branches:
      - v0.38.x-celestia

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            docs/architecture/**
            docs/rfc/**
      - run: make check-docs-toc
        if: env.GIT_DIFF
