name: e2e
# Runs the CI end-to-end test network on all pushes to v0.38.x-celestia and main
# and every pull request, but only if any Go files have been changed.
on:
  workflow_dispatch:  # allow running workflow manually
  pull_request:
  merge_group:
  push:
    branches:
      - v0.38.x-celestia
      - main

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum

      - name: Build
        working-directory: test/e2e
        # Run two make jobs in parallel, since we can't run steps in parallel.
        run: make -j2 docker runner tests
        if: "env.GIT_DIFF != ''"

      - name: Run CI testnets
        working-directory: test/e2e
        run: ./run-multiple.sh networks/ci.toml networks/propagation-reactor-compatibility.toml
        if: "env.GIT_DIFF != ''"
