name: Golang Linter
# Lint runs golangci-lint over the entire CometBFT repository.
#
# This workflow is run on every pull request and push to v0.38.x-celestia and main.
#
# To run this locally, simply run `make lint` from the root of the repo.

on:
  pull_request:
  merge_group:
  push:
    branches:
      - v0.38.x-celestia
      - main
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
