name: Golang Linter
# Lint runs golangci-lint over the entire CometBFT repository.
#
# This workflow is run on every pull request and push to main.
#
# The `golangci` job will pass without running if no *.{go, mod, sum}
# files have been modified.
#
# To run this locally, simply run `make lint` from the root of the repo.

on:
  pull_request:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  push:
    branches:
      - main
      - v[0-9]+.[0-9]+.x-celestia
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - uses: golangci/golangci-lint-action@v7.0.0
        with:
          # Required: the version of golangci-lint is required and
          # must be specified without patch version: we always use the
          # latest patch version.
          version: v1.55.2
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
