name: Test
on:
  pull_request:
  merge_group:
  push:
    paths:
      - "**.go"
    branches:
      - v0.38.x-celestia
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        part: ["00", "01", "02", "03", "04", "05"]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"
      - uses: technote-space/get-diff-action@f27caffdd0fb9b13f4fc191c016bb4e0632844af # v6
        with:
          PATTERNS: |
            **/**.go
            "!test/"
            go.mod
            go.sum
            Makefile
            .github/workflows/tests.yml
      - name: Run Go Tests
        run: |
          make test-group-${{ matrix.part }} NUM_SPLIT=6
        if: env.GIT_DIFF
      - name: Upload coverage
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          disable_search: true
          fail_ci_if_error: true
          files: ./build/${{ matrix.part }}.profile.out
          name: unit-${{ matrix.part }}
          use_oidc: true
        if: env.GIT_DIFF
